#!/bin/bash

# Name: compress-initramfs
# Author: Ruulian
# Version: v1.0
# Github page: https://github.com/Ruulian/initramfs-toolkit



INPUT_FILE=""
INPUT_DEFAULT="."

INPUT_DIR=$INPUT_DEFAULT

print_help() {
    echo "Usage: $0 [-o output_initramfs] [-i input_directory]"
    echo "Options:"
    echo "  -o : Specify the input directory (default: '$INPUT_DEFAULT')"
    echo "  -h : Print this help message"
}

if [ ! -f "$1" ]; then
    print_help
    exit
fi


# Parse options
while [[ $# -gt 0 ]]; do
    case "$1" in
        -i )
            INPUT_DIR="$2"
            shift 2
            ;;
        -h )
            print_help
            exit 0
            ;;
        * )
            OUTPUT_FILE="$1"
            shift
            ;;
    esac
done

if [ -z "$OUTPUT_FILE" ]; then
    print_help
    exit 1
fi

SCRIPTPATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"

# gzip | bzip2 | lz4 | lzma | lzop | xz | zstd
declare -a exts=(gzip bzip2 lz4 lzma lzop xz zstd)

INITRAMFS="$(realpath $INPUT_FILE)"
FILE_TYPE=$(cat "$INITRAMFS" | file -)
TMP_EXTRACTED="bf072e_extracted.cpio"

